version: '3.7'
services:
  vpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn
    restart: unless-stopped
    tty: true
    ports:
      - 4500:4500
      - 500:500
    cap_add:
      - ALL
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true
